{{- if .Values.vault_settings.azure_key_vault }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.csi.csi_default_name }}
spec:
  provider: azure
  secretObjects:
  - data:
    - key: meta-agent-api-key
      objectName: meta-agent-api-key
    - key: keycloak-certs-endpoint
      objectName: keycloak-certs-endpoint
    - key: message-broker-driver
      objectName: message-broker-driver
    - key: message-broker-connection-string
      objectName: message-broker-connection-string
    - key: database-host
      objectName: database-host
    - key: database-db
      objectName: meta-agent-database-db
    - key: user
      objectName: meta-agent-user
    - key: password
      objectName: meta-agent-password
    secretName: {{ .Values.secrets.deps_meta_agent.secretName }}
    type: Opaque
  parameters:
    keyvaultName: {{ .Values.azure_kv_settings.keyvaultName }}
    tenantId: {{ .Values.azure_kv_settings.tenantId }}
    vaultKubernetesMountPath: {{ .Values.csi.vaultKubernetesMountPath }}
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.azure_kv_settings.userAssignedIdentityID }}
    resourceGroup:  {{ .Values.azure_kv_settings.resourceGroup }}
    subscriptionId: {{ .Values.azure_kv_settings.subscriptionId }}
    objects: |
      array:
        - |
          objectName: "meta-agent-api-key"
          objectType: secret

        - |
          objectName: "keycloak-certs-endpoint"
          objectType: secret

        - |
          objectName: "message-broker-connection-string"
          objectType: secret

        - |
          objectName: "message-broker-driver"
          objectType: secret

        - |
          objectName: "database-host"
          objectType: secret
      
        - |
          objectName: "meta-agent-database-db"
          objectType: secret

        - |
          objectName: "meta-agent-user"
          objectType: secret

        - |
          objectName: "meta-agent-password"
          objectType: secret
{{- end }}
