{{- if .Values.vault_settings.azure_key_vault }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.csi.csi_default_name }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "3"
spec:
  provider: azure
  secretObjects:
  - data:
    - key: database-host
      objectName: database-host
    - key: database-db
      objectName: meta-agent-database-db
    - key: user
      objectName: meta-agent-user
    - key: password
      objectName: meta-agent-password
    secretName: {{ .Values.secrets.deps_meta_agent_migrator.secretName }}
    type: Opaque
  parameters:
    keyvaultName: {{ .Values.azure_kv_settings.keyvaultName }}
    tenantId: {{ .Values.azure_kv_settings.tenantId }}
    vaultKubernetesMountPath: {{ .Values.csi.vaultKubernetesMountPath }}
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.azure_kv_settings.userAssignedIdentityID }}
    resourceGroup:  {{ .Values.azure_kv_settings.resourceGroup }}
    subscriptionId: {{ .Values.azure_kv_settings.subscriptionId }}
    objects: |
      array:
        - |
          objectName: "database-host"
          objectType: secret
      
        - |
          objectName: "meta-agent-database-db"
          objectType: secret

        - |
          objectName: "meta-agent-user"
          objectType: secret

        - |
          objectName: "meta-agent-password"
          objectType: secret
{{- end }}
